//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLDiemSV_Entities : DbContext
    {
        public QLDiemSV_Entities()
            : base("name=QLDiemSV_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Diem> Diems { get; set; }
        public virtual DbSet<HeDT> HeDTs { get; set; }
        public virtual DbSet<Khoa> Khoas { get; set; }
        public virtual DbSet<KhoaHoc> KhoaHocs { get; set; }
        public virtual DbSet<Lop> Lops { get; set; }
        public virtual DbSet<MonHoc> MonHocs { get; set; }
        public virtual DbSet<SinhVien> SinhViens { get; set; }
        public virtual DbSet<GiangVien> GiangViens { get; set; }
        public virtual DbSet<LopHocPhan> LopHocPhans { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Courses_Info> Courses_Info { get; set; }
        public virtual DbSet<Score> Scores { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        [DbFunction("QLDiemSV_Entities", "FindStudent")]
        public virtual IQueryable<FindStudent_Result> FindStudent(string maSV)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("MaSV", maSV) :
                new ObjectParameter("MaSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FindStudent_Result>("[QLDiemSV_Entities].[FindStudent](@MaSV)", maSVParameter);
        }
    
        [DbFunction("QLDiemSV_Entities", "FindStudentWithHighestScore")]
        public virtual IQueryable<FindStudentWithHighestScore_Result> FindStudentWithHighestScore()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FindStudentWithHighestScore_Result>("[QLDiemSV_Entities].[FindStudentWithHighestScore]()");
        }
    
        public virtual ObjectResult<hienthisv_diem_Result> hienthisv_diem()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hienthisv_diem_Result>("hienthisv_diem");
        }
    
        public virtual int nhapmoiSV(string masv, string tensv, Nullable<bool> gioitinh, Nullable<System.DateTime> ngaysinh, string quequan, string malop)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("Masv", masv) :
                new ObjectParameter("Masv", typeof(string));
    
            var tensvParameter = tensv != null ?
                new ObjectParameter("Tensv", tensv) :
                new ObjectParameter("Tensv", typeof(string));
    
            var gioitinhParameter = gioitinh.HasValue ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(bool));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var quequanParameter = quequan != null ?
                new ObjectParameter("quequan", quequan) :
                new ObjectParameter("quequan", typeof(string));
    
            var malopParameter = malop != null ?
                new ObjectParameter("malop", malop) :
                new ObjectParameter("malop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("nhapmoiSV", masvParameter, tensvParameter, gioitinhParameter, ngaysinhParameter, quequanParameter, malopParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_delDIEM(string mASV)
        {
            var mASVParameter = mASV != null ?
                new ObjectParameter("MASV", mASV) :
                new ObjectParameter("MASV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delDIEM", mASVParameter);
        }
    
        public virtual int sp_delGiangVien(Nullable<int> maGV)
        {
            var maGVParameter = maGV.HasValue ?
                new ObjectParameter("MaGV", maGV) :
                new ObjectParameter("MaGV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delGiangVien", maGVParameter);
        }
    
        public virtual int sp_delHEDT(string maHeDT)
        {
            var maHeDTParameter = maHeDT != null ?
                new ObjectParameter("MaHeDT", maHeDT) :
                new ObjectParameter("MaHeDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delHEDT", maHeDTParameter);
        }
    
        public virtual int sp_delKHOA(string mAKHOA)
        {
            var mAKHOAParameter = mAKHOA != null ?
                new ObjectParameter("MAKHOA", mAKHOA) :
                new ObjectParameter("MAKHOA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delKHOA", mAKHOAParameter);
        }
    
        public virtual int sp_delKHOAHOC(string maKhoaHoc)
        {
            var maKhoaHocParameter = maKhoaHoc != null ?
                new ObjectParameter("MaKhoaHoc", maKhoaHoc) :
                new ObjectParameter("MaKhoaHoc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delKHOAHOC", maKhoaHocParameter);
        }
    
        public virtual int sp_delLOP(string mALOP)
        {
            var mALOPParameter = mALOP != null ?
                new ObjectParameter("MALOP", mALOP) :
                new ObjectParameter("MALOP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delLOP", mALOPParameter);
        }
    
        public virtual int sp_delLopHocPhan(string maLHP)
        {
            var maLHPParameter = maLHP != null ?
                new ObjectParameter("MaLHP", maLHP) :
                new ObjectParameter("MaLHP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delLopHocPhan", maLHPParameter);
        }
    
        public virtual int sp_delMONHOC(string mAMH)
        {
            var mAMHParameter = mAMH != null ?
                new ObjectParameter("MAMH", mAMH) :
                new ObjectParameter("MAMH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delMONHOC", mAMHParameter);
        }
    
        public virtual int sp_delSINHVIEN(string mASV)
        {
            var mASVParameter = mASV != null ?
                new ObjectParameter("MASV", mASV) :
                new ObjectParameter("MASV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delSINHVIEN", mASVParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_HEDT(string maHeDT, string tenHeDT)
        {
            var maHeDTParameter = maHeDT != null ?
                new ObjectParameter("MaHeDT", maHeDT) :
                new ObjectParameter("MaHeDT", typeof(string));
    
            var tenHeDTParameter = tenHeDT != null ?
                new ObjectParameter("TenHeDT", tenHeDT) :
                new ObjectParameter("TenHeDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_HEDT", maHeDTParameter, tenHeDTParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_insDIEM(string maSV, string maMH, Nullable<int> hocKy, Nullable<double> diemQuaTrinh, Nullable<double> diemCuoiKy)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("MaSV", maSV) :
                new ObjectParameter("MaSV", typeof(string));
    
            var maMHParameter = maMH != null ?
                new ObjectParameter("MaMH", maMH) :
                new ObjectParameter("MaMH", typeof(string));
    
            var hocKyParameter = hocKy.HasValue ?
                new ObjectParameter("HocKy", hocKy) :
                new ObjectParameter("HocKy", typeof(int));
    
            var diemQuaTrinhParameter = diemQuaTrinh.HasValue ?
                new ObjectParameter("DiemQuaTrinh", diemQuaTrinh) :
                new ObjectParameter("DiemQuaTrinh", typeof(double));
    
            var diemCuoiKyParameter = diemCuoiKy.HasValue ?
                new ObjectParameter("DiemCuoiKy", diemCuoiKy) :
                new ObjectParameter("DiemCuoiKy", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insDIEM", maSVParameter, maMHParameter, hocKyParameter, diemQuaTrinhParameter, diemCuoiKyParameter);
        }
    
        public virtual int sp_insGiangVien(Nullable<int> maGV, string tenGV, Nullable<int> maKhoa, string diaChi, string sDT)
        {
            var maGVParameter = maGV.HasValue ?
                new ObjectParameter("MaGV", maGV) :
                new ObjectParameter("MaGV", typeof(int));
    
            var tenGVParameter = tenGV != null ?
                new ObjectParameter("TenGV", tenGV) :
                new ObjectParameter("TenGV", typeof(string));
    
            var maKhoaParameter = maKhoa.HasValue ?
                new ObjectParameter("MaKhoa", maKhoa) :
                new ObjectParameter("MaKhoa", typeof(int));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insGiangVien", maGVParameter, tenGVParameter, maKhoaParameter, diaChiParameter, sDTParameter);
        }
    
        public virtual int sp_insKHOA(string maKhoa, string tenKhoa, string diaChi, string dienThoai)
        {
            var maKhoaParameter = maKhoa != null ?
                new ObjectParameter("MaKhoa", maKhoa) :
                new ObjectParameter("MaKhoa", typeof(string));
    
            var tenKhoaParameter = tenKhoa != null ?
                new ObjectParameter("TenKhoa", tenKhoa) :
                new ObjectParameter("TenKhoa", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("DienThoai", dienThoai) :
                new ObjectParameter("DienThoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insKHOA", maKhoaParameter, tenKhoaParameter, diaChiParameter, dienThoaiParameter);
        }
    
        public virtual int sp_insKHOAHOC(string maKhoaHoc, string tenKhoaHoc)
        {
            var maKhoaHocParameter = maKhoaHoc != null ?
                new ObjectParameter("MaKhoaHoc", maKhoaHoc) :
                new ObjectParameter("MaKhoaHoc", typeof(string));
    
            var tenKhoaHocParameter = tenKhoaHoc != null ?
                new ObjectParameter("TenKhoaHoc", tenKhoaHoc) :
                new ObjectParameter("TenKhoaHoc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insKHOAHOC", maKhoaHocParameter, tenKhoaHocParameter);
        }
    
        public virtual int sp_insLOP(string mALOP, string tENLOP, string mAKHOA, string maHeDT, string maKhoaHoc)
        {
            var mALOPParameter = mALOP != null ?
                new ObjectParameter("MALOP", mALOP) :
                new ObjectParameter("MALOP", typeof(string));
    
            var tENLOPParameter = tENLOP != null ?
                new ObjectParameter("TENLOP", tENLOP) :
                new ObjectParameter("TENLOP", typeof(string));
    
            var mAKHOAParameter = mAKHOA != null ?
                new ObjectParameter("MAKHOA", mAKHOA) :
                new ObjectParameter("MAKHOA", typeof(string));
    
            var maHeDTParameter = maHeDT != null ?
                new ObjectParameter("MaHeDT", maHeDT) :
                new ObjectParameter("MaHeDT", typeof(string));
    
            var maKhoaHocParameter = maKhoaHoc != null ?
                new ObjectParameter("MaKhoaHoc", maKhoaHoc) :
                new ObjectParameter("MaKhoaHoc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insLOP", mALOPParameter, tENLOPParameter, mAKHOAParameter, maHeDTParameter, maKhoaHocParameter);
        }
    
        public virtual int sp_insLopHocPhan(string maLHP, string maMH, string maKhoaHoc, Nullable<int> namHoc, Nullable<int> maGV, Nullable<int> siSoSV)
        {
            var maLHPParameter = maLHP != null ?
                new ObjectParameter("MaLHP", maLHP) :
                new ObjectParameter("MaLHP", typeof(string));
    
            var maMHParameter = maMH != null ?
                new ObjectParameter("MaMH", maMH) :
                new ObjectParameter("MaMH", typeof(string));
    
            var maKhoaHocParameter = maKhoaHoc != null ?
                new ObjectParameter("MaKhoaHoc", maKhoaHoc) :
                new ObjectParameter("MaKhoaHoc", typeof(string));
    
            var namHocParameter = namHoc.HasValue ?
                new ObjectParameter("NamHoc", namHoc) :
                new ObjectParameter("NamHoc", typeof(int));
    
            var maGVParameter = maGV.HasValue ?
                new ObjectParameter("MaGV", maGV) :
                new ObjectParameter("MaGV", typeof(int));
    
            var siSoSVParameter = siSoSV.HasValue ?
                new ObjectParameter("SiSoSV", siSoSV) :
                new ObjectParameter("SiSoSV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insLopHocPhan", maLHPParameter, maMHParameter, maKhoaHocParameter, namHocParameter, maGVParameter, siSoSVParameter);
        }
    
        public virtual int sp_insMONHOC(string maMH, string tenMH, Nullable<int> soTinChi)
        {
            var maMHParameter = maMH != null ?
                new ObjectParameter("MaMH", maMH) :
                new ObjectParameter("MaMH", typeof(string));
    
            var tenMHParameter = tenMH != null ?
                new ObjectParameter("TenMH", tenMH) :
                new ObjectParameter("TenMH", typeof(string));
    
            var soTinChiParameter = soTinChi.HasValue ?
                new ObjectParameter("SoTinChi", soTinChi) :
                new ObjectParameter("SoTinChi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insMONHOC", maMHParameter, tenMHParameter, soTinChiParameter);
        }
    
        public virtual int sp_insSINHVIEN(string mASV, string tENSV, Nullable<bool> gIOITINH, Nullable<System.DateTime> nGAYSINH, string queQuan, string mALOP)
        {
            var mASVParameter = mASV != null ?
                new ObjectParameter("MASV", mASV) :
                new ObjectParameter("MASV", typeof(string));
    
            var tENSVParameter = tENSV != null ?
                new ObjectParameter("TENSV", tENSV) :
                new ObjectParameter("TENSV", typeof(string));
    
            var gIOITINHParameter = gIOITINH.HasValue ?
                new ObjectParameter("GIOITINH", gIOITINH) :
                new ObjectParameter("GIOITINH", typeof(bool));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var queQuanParameter = queQuan != null ?
                new ObjectParameter("QueQuan", queQuan) :
                new ObjectParameter("QueQuan", typeof(string));
    
            var mALOPParameter = mALOP != null ?
                new ObjectParameter("MALOP", mALOP) :
                new ObjectParameter("MALOP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insSINHVIEN", mASVParameter, tENSVParameter, gIOITINHParameter, nGAYSINHParameter, queQuanParameter, mALOPParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<sp_showDIEM_Result> sp_showDIEM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_showDIEM_Result>("sp_showDIEM");
        }
    
        public virtual ObjectResult<sp_showHEDT_Result> sp_showHEDT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_showHEDT_Result>("sp_showHEDT");
        }
    
        public virtual ObjectResult<sp_showKHOA_Result> sp_showKHOA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_showKHOA_Result>("sp_showKHOA");
        }
    
        public virtual ObjectResult<sp_showKHOAHOC_Result> sp_showKHOAHOC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_showKHOAHOC_Result>("sp_showKHOAHOC");
        }
    
        public virtual ObjectResult<sp_showLOP_Result> sp_showLOP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_showLOP_Result>("sp_showLOP");
        }
    
        public virtual ObjectResult<sp_showMONHOC_Result> sp_showMONHOC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_showMONHOC_Result>("sp_showMONHOC");
        }
    
        public virtual ObjectResult<sp_showSINHVIEN_Result> sp_showSINHVIEN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_showSINHVIEN_Result>("sp_showSINHVIEN");
        }
    
        public virtual int sp_updateDIEM(string maSV, string maMH, Nullable<int> hocKy, Nullable<double> diemQuaTrinh, Nullable<double> diemCuoiKy)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("MaSV", maSV) :
                new ObjectParameter("MaSV", typeof(string));
    
            var maMHParameter = maMH != null ?
                new ObjectParameter("MaMH", maMH) :
                new ObjectParameter("MaMH", typeof(string));
    
            var hocKyParameter = hocKy.HasValue ?
                new ObjectParameter("HocKy", hocKy) :
                new ObjectParameter("HocKy", typeof(int));
    
            var diemQuaTrinhParameter = diemQuaTrinh.HasValue ?
                new ObjectParameter("DiemQuaTrinh", diemQuaTrinh) :
                new ObjectParameter("DiemQuaTrinh", typeof(double));
    
            var diemCuoiKyParameter = diemCuoiKy.HasValue ?
                new ObjectParameter("DiemCuoiKy", diemCuoiKy) :
                new ObjectParameter("DiemCuoiKy", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_updateDIEM", maSVParameter, maMHParameter, hocKyParameter, diemQuaTrinhParameter, diemCuoiKyParameter);
        }
    
        public virtual int sp_updateGiangVien(Nullable<int> maGV, string tenGV, Nullable<int> maKhoa, string diaChi, string sDT)
        {
            var maGVParameter = maGV.HasValue ?
                new ObjectParameter("MaGV", maGV) :
                new ObjectParameter("MaGV", typeof(int));
    
            var tenGVParameter = tenGV != null ?
                new ObjectParameter("TenGV", tenGV) :
                new ObjectParameter("TenGV", typeof(string));
    
            var maKhoaParameter = maKhoa.HasValue ?
                new ObjectParameter("MaKhoa", maKhoa) :
                new ObjectParameter("MaKhoa", typeof(int));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_updateGiangVien", maGVParameter, tenGVParameter, maKhoaParameter, diaChiParameter, sDTParameter);
        }
    
        public virtual int sp_updateHEDT(string maHeDT, string tenHeDT)
        {
            var maHeDTParameter = maHeDT != null ?
                new ObjectParameter("MaHeDT", maHeDT) :
                new ObjectParameter("MaHeDT", typeof(string));
    
            var tenHeDTParameter = tenHeDT != null ?
                new ObjectParameter("TenHeDT", tenHeDT) :
                new ObjectParameter("TenHeDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_updateHEDT", maHeDTParameter, tenHeDTParameter);
        }
    
        public virtual int sp_updateKHOA(string maKhoa, string tenKhoa, string diaChi, string dienThoai)
        {
            var maKhoaParameter = maKhoa != null ?
                new ObjectParameter("MaKhoa", maKhoa) :
                new ObjectParameter("MaKhoa", typeof(string));
    
            var tenKhoaParameter = tenKhoa != null ?
                new ObjectParameter("TenKhoa", tenKhoa) :
                new ObjectParameter("TenKhoa", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("DienThoai", dienThoai) :
                new ObjectParameter("DienThoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_updateKHOA", maKhoaParameter, tenKhoaParameter, diaChiParameter, dienThoaiParameter);
        }
    
        public virtual int sp_updateKHOAHOC(string maKhoaHoc, string tenKhoaHoc)
        {
            var maKhoaHocParameter = maKhoaHoc != null ?
                new ObjectParameter("MaKhoaHoc", maKhoaHoc) :
                new ObjectParameter("MaKhoaHoc", typeof(string));
    
            var tenKhoaHocParameter = tenKhoaHoc != null ?
                new ObjectParameter("TenKhoaHoc", tenKhoaHoc) :
                new ObjectParameter("TenKhoaHoc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_updateKHOAHOC", maKhoaHocParameter, tenKhoaHocParameter);
        }
    
        public virtual int sp_updateLOP(string mALOP, string tENLOP, string mAKHOA, string maHeDT, string maKhoaHoc)
        {
            var mALOPParameter = mALOP != null ?
                new ObjectParameter("MALOP", mALOP) :
                new ObjectParameter("MALOP", typeof(string));
    
            var tENLOPParameter = tENLOP != null ?
                new ObjectParameter("TENLOP", tENLOP) :
                new ObjectParameter("TENLOP", typeof(string));
    
            var mAKHOAParameter = mAKHOA != null ?
                new ObjectParameter("MAKHOA", mAKHOA) :
                new ObjectParameter("MAKHOA", typeof(string));
    
            var maHeDTParameter = maHeDT != null ?
                new ObjectParameter("MaHeDT", maHeDT) :
                new ObjectParameter("MaHeDT", typeof(string));
    
            var maKhoaHocParameter = maKhoaHoc != null ?
                new ObjectParameter("MaKhoaHoc", maKhoaHoc) :
                new ObjectParameter("MaKhoaHoc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_updateLOP", mALOPParameter, tENLOPParameter, mAKHOAParameter, maHeDTParameter, maKhoaHocParameter);
        }
    
        public virtual int sp_updateLopHocPhan(string maLHP, string maMH, string maKhoaHoc, Nullable<int> namHoc, Nullable<int> maGV, Nullable<int> siSoSV)
        {
            var maLHPParameter = maLHP != null ?
                new ObjectParameter("MaLHP", maLHP) :
                new ObjectParameter("MaLHP", typeof(string));
    
            var maMHParameter = maMH != null ?
                new ObjectParameter("MaMH", maMH) :
                new ObjectParameter("MaMH", typeof(string));
    
            var maKhoaHocParameter = maKhoaHoc != null ?
                new ObjectParameter("MaKhoaHoc", maKhoaHoc) :
                new ObjectParameter("MaKhoaHoc", typeof(string));
    
            var namHocParameter = namHoc.HasValue ?
                new ObjectParameter("NamHoc", namHoc) :
                new ObjectParameter("NamHoc", typeof(int));
    
            var maGVParameter = maGV.HasValue ?
                new ObjectParameter("MaGV", maGV) :
                new ObjectParameter("MaGV", typeof(int));
    
            var siSoSVParameter = siSoSV.HasValue ?
                new ObjectParameter("SiSoSV", siSoSV) :
                new ObjectParameter("SiSoSV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_updateLopHocPhan", maLHPParameter, maMHParameter, maKhoaHocParameter, namHocParameter, maGVParameter, siSoSVParameter);
        }
    
        public virtual int sp_updateMONHOC(string maMH, string tenMH, Nullable<int> soTinChi)
        {
            var maMHParameter = maMH != null ?
                new ObjectParameter("MaMH", maMH) :
                new ObjectParameter("MaMH", typeof(string));
    
            var tenMHParameter = tenMH != null ?
                new ObjectParameter("TenMH", tenMH) :
                new ObjectParameter("TenMH", typeof(string));
    
            var soTinChiParameter = soTinChi.HasValue ?
                new ObjectParameter("SoTinChi", soTinChi) :
                new ObjectParameter("SoTinChi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_updateMONHOC", maMHParameter, tenMHParameter, soTinChiParameter);
        }
    
        public virtual int sp_updateSINHVIEN(string mASV, string tENSV, Nullable<bool> gIOITINH, Nullable<System.DateTime> nGAYSINH, string qUEQUAN, string mALOP)
        {
            var mASVParameter = mASV != null ?
                new ObjectParameter("MASV", mASV) :
                new ObjectParameter("MASV", typeof(string));
    
            var tENSVParameter = tENSV != null ?
                new ObjectParameter("TENSV", tENSV) :
                new ObjectParameter("TENSV", typeof(string));
    
            var gIOITINHParameter = gIOITINH.HasValue ?
                new ObjectParameter("GIOITINH", gIOITINH) :
                new ObjectParameter("GIOITINH", typeof(bool));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var qUEQUANParameter = qUEQUAN != null ?
                new ObjectParameter("QUEQUAN", qUEQUAN) :
                new ObjectParameter("QUEQUAN", typeof(string));
    
            var mALOPParameter = mALOP != null ?
                new ObjectParameter("MALOP", mALOP) :
                new ObjectParameter("MALOP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_updateSINHVIEN", mASVParameter, tENSVParameter, gIOITINHParameter, nGAYSINHParameter, qUEQUANParameter, mALOPParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
