//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public string MaSV { get; set; }
        public string TenSV { get; set; }
        public bool GioiTinh { get; set; }
        public string MaLop { get; set; }
        public string TenMH { get; set; }
        public int HocKy { get; set; }
        public Nullable<double> DiemQuaTrinh { get; set; }
        public Nullable<double> DiemCuoiKy { get; set; }
        public Nullable<double> DiemTrungBinh { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
    }
}
